package org.java.bi.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.bi.db.domain.BDicTreeCode;
import org.java.bi.db.domain.BDicTreeCodeExample;

public interface BDicTreeCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     */
    long countByExample(BDicTreeCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     */
    int deleteByExample(BDicTreeCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     */
    int insert(BDicTreeCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     */
    int insertSelective(BDicTreeCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BDicTreeCode selectOneByExample(BDicTreeCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BDicTreeCode selectOneByExampleSelective(@Param("example") BDicTreeCodeExample example, @Param("selective") BDicTreeCode.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<BDicTreeCode> selectByExampleSelective(@Param("example") BDicTreeCodeExample example, @Param("selective") BDicTreeCode.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     */
    List<BDicTreeCode> selectByExample(BDicTreeCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BDicTreeCode selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") BDicTreeCode.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     */
    BDicTreeCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    BDicTreeCode selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BDicTreeCode record, @Param("example") BDicTreeCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BDicTreeCode record, @Param("example") BDicTreeCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BDicTreeCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BDicTreeCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") BDicTreeCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_dic_tree_code
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}