package org.java.bi.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.bi.db.domain.SysBiUser;
import org.java.bi.db.domain.SysBiUserExample;

public interface SysBiUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     */
    long countByExample(SysBiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     */
    int deleteByExample(SysBiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     */
    int insert(SysBiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     */
    int insertSelective(SysBiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysBiUser selectOneByExample(SysBiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysBiUser selectOneByExampleSelective(@Param("example") SysBiUserExample example, @Param("selective") SysBiUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SysBiUser> selectByExampleSelective(@Param("example") SysBiUserExample example, @Param("selective") SysBiUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     */
    List<SysBiUser> selectByExample(SysBiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysBiUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SysBiUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     */
    SysBiUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysBiUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysBiUser record, @Param("example") SysBiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysBiUser record, @Param("example") SysBiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysBiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysBiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SysBiUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}