package org.java.bi.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.bi.db.domain.SysBiMenu;
import org.java.bi.db.domain.SysBiMenuExample;

public interface SysBiMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     */
    long countByExample(SysBiMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     */
    int deleteByExample(SysBiMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     */
    int insert(SysBiMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     */
    int insertSelective(SysBiMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysBiMenu selectOneByExample(SysBiMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysBiMenu selectOneByExampleSelective(@Param("example") SysBiMenuExample example, @Param("selective") SysBiMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<SysBiMenu> selectByExampleSelective(@Param("example") SysBiMenuExample example, @Param("selective") SysBiMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     */
    List<SysBiMenu> selectByExample(SysBiMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysBiMenu selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") SysBiMenu.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     */
    SysBiMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    SysBiMenu selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysBiMenu record, @Param("example") SysBiMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysBiMenu record, @Param("example") SysBiMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysBiMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysBiMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") SysBiMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_bi_menu
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}