package org.java.bi.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.bi.db.domain.ViewTableFieldDef;
import org.java.bi.db.domain.ViewTableFieldDefExample;
import org.java.bi.db.domain.ViewTableFieldDefWithBLOBs;

public interface ViewTableFieldDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    long countByExample(ViewTableFieldDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    int deleteByExample(ViewTableFieldDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    int insert(ViewTableFieldDefWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    int insertSelective(ViewTableFieldDefWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewTableFieldDef selectOneByExample(ViewTableFieldDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewTableFieldDefWithBLOBs selectOneByExampleSelective(@Param("example") ViewTableFieldDefExample example, @Param("selective") ViewTableFieldDefWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewTableFieldDefWithBLOBs selectOneByExampleWithBLOBs(ViewTableFieldDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewTableFieldDefWithBLOBs> selectByExampleSelective(@Param("example") ViewTableFieldDefExample example, @Param("selective") ViewTableFieldDefWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    List<ViewTableFieldDefWithBLOBs> selectByExampleWithBLOBs(ViewTableFieldDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    List<ViewTableFieldDef> selectByExample(ViewTableFieldDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewTableFieldDefWithBLOBs record, @Param("example") ViewTableFieldDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ViewTableFieldDefWithBLOBs record, @Param("example") ViewTableFieldDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewTableFieldDef record, @Param("example") ViewTableFieldDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewTableFieldDefExample example);
}