package org.java.bi.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.java.bi.db.domain.ViewTableDef;
import org.java.bi.db.domain.ViewTableDefExample;

public interface ViewTableDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_def
     *
     * @mbg.generated
     */
    long countByExample(ViewTableDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_def
     *
     * @mbg.generated
     */
    int deleteByExample(ViewTableDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_def
     *
     * @mbg.generated
     */
    int insert(ViewTableDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_def
     *
     * @mbg.generated
     */
    int insertSelective(ViewTableDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewTableDef selectOneByExample(ViewTableDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ViewTableDef selectOneByExampleSelective(@Param("example") ViewTableDefExample example, @Param("selective") ViewTableDef.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ViewTableDef> selectByExampleSelective(@Param("example") ViewTableDefExample example, @Param("selective") ViewTableDef.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_def
     *
     * @mbg.generated
     */
    List<ViewTableDef> selectByExample(ViewTableDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_def
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ViewTableDef record, @Param("example") ViewTableDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_def
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ViewTableDef record, @Param("example") ViewTableDefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ViewTableDefExample example);
}