package org.java.bi.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class SysTableDesp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_table_desp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_table_desp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean IS_DELETED = true;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.olt_table_desp
     *
     * @mbg.generated
     */
    private String oltTableDesp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.olt_primary_field_name
     *
     * @mbg.generated
     */
    private String oltPrimaryFieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.olt_remark
     *
     * @mbg.generated
     */
    private String oltRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.olt_parent_id
     *
     * @mbg.generated
     */
    private Integer oltParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.olt_unique_field_names
     *
     * @mbg.generated
     */
    private String[] oltUniqueFieldNames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.olt_unique_field_deps
     *
     * @mbg.generated
     */
    private String[] oltUniqueFieldDeps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.olt_foreign_field_name
     *
     * @mbg.generated
     */
    private String oltForeignFieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.olt_foreign_field_des
     *
     * @mbg.generated
     */
    private String oltForeignFieldDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.ordernumber
     *
     * @mbg.generated
     */
    private Integer ordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.olt_db_talbe_view_name
     *
     * @mbg.generated
     */
    private String oltDbTalbeViewName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.olt_db_talbe_view_desc
     *
     * @mbg.generated
     */
    private String oltDbTalbeViewDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.olt_json_package_name
     *
     * @mbg.generated
     */
    private String oltJsonPackageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.tenant_id
     *
     * @mbg.generated
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.add_by
     *
     * @mbg.generated
     */
    private String addBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_desp.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.id
     *
     * @return the value of sys_table_desp.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.id
     *
     * @param id the value for sys_table_desp.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.olt_table_desp
     *
     * @return the value of sys_table_desp.olt_table_desp
     *
     * @mbg.generated
     */
    public String getOltTableDesp() {
        return oltTableDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.olt_table_desp
     *
     * @param oltTableDesp the value for sys_table_desp.olt_table_desp
     *
     * @mbg.generated
     */
    public void setOltTableDesp(String oltTableDesp) {
        this.oltTableDesp = oltTableDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.olt_primary_field_name
     *
     * @return the value of sys_table_desp.olt_primary_field_name
     *
     * @mbg.generated
     */
    public String getOltPrimaryFieldName() {
        return oltPrimaryFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.olt_primary_field_name
     *
     * @param oltPrimaryFieldName the value for sys_table_desp.olt_primary_field_name
     *
     * @mbg.generated
     */
    public void setOltPrimaryFieldName(String oltPrimaryFieldName) {
        this.oltPrimaryFieldName = oltPrimaryFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.olt_remark
     *
     * @return the value of sys_table_desp.olt_remark
     *
     * @mbg.generated
     */
    public String getOltRemark() {
        return oltRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.olt_remark
     *
     * @param oltRemark the value for sys_table_desp.olt_remark
     *
     * @mbg.generated
     */
    public void setOltRemark(String oltRemark) {
        this.oltRemark = oltRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.olt_parent_id
     *
     * @return the value of sys_table_desp.olt_parent_id
     *
     * @mbg.generated
     */
    public Integer getOltParentId() {
        return oltParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.olt_parent_id
     *
     * @param oltParentId the value for sys_table_desp.olt_parent_id
     *
     * @mbg.generated
     */
    public void setOltParentId(Integer oltParentId) {
        this.oltParentId = oltParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.olt_unique_field_names
     *
     * @return the value of sys_table_desp.olt_unique_field_names
     *
     * @mbg.generated
     */
    public String[] getOltUniqueFieldNames() {
        return oltUniqueFieldNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.olt_unique_field_names
     *
     * @param oltUniqueFieldNames the value for sys_table_desp.olt_unique_field_names
     *
     * @mbg.generated
     */
    public void setOltUniqueFieldNames(String[] oltUniqueFieldNames) {
        this.oltUniqueFieldNames = oltUniqueFieldNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.olt_unique_field_deps
     *
     * @return the value of sys_table_desp.olt_unique_field_deps
     *
     * @mbg.generated
     */
    public String[] getOltUniqueFieldDeps() {
        return oltUniqueFieldDeps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.olt_unique_field_deps
     *
     * @param oltUniqueFieldDeps the value for sys_table_desp.olt_unique_field_deps
     *
     * @mbg.generated
     */
    public void setOltUniqueFieldDeps(String[] oltUniqueFieldDeps) {
        this.oltUniqueFieldDeps = oltUniqueFieldDeps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.olt_foreign_field_name
     *
     * @return the value of sys_table_desp.olt_foreign_field_name
     *
     * @mbg.generated
     */
    public String getOltForeignFieldName() {
        return oltForeignFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.olt_foreign_field_name
     *
     * @param oltForeignFieldName the value for sys_table_desp.olt_foreign_field_name
     *
     * @mbg.generated
     */
    public void setOltForeignFieldName(String oltForeignFieldName) {
        this.oltForeignFieldName = oltForeignFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.olt_foreign_field_des
     *
     * @return the value of sys_table_desp.olt_foreign_field_des
     *
     * @mbg.generated
     */
    public String getOltForeignFieldDes() {
        return oltForeignFieldDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.olt_foreign_field_des
     *
     * @param oltForeignFieldDes the value for sys_table_desp.olt_foreign_field_des
     *
     * @mbg.generated
     */
    public void setOltForeignFieldDes(String oltForeignFieldDes) {
        this.oltForeignFieldDes = oltForeignFieldDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.ordernumber
     *
     * @return the value of sys_table_desp.ordernumber
     *
     * @mbg.generated
     */
    public Integer getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.ordernumber
     *
     * @param ordernumber the value for sys_table_desp.ordernumber
     *
     * @mbg.generated
     */
    public void setOrdernumber(Integer ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.olt_db_talbe_view_name
     *
     * @return the value of sys_table_desp.olt_db_talbe_view_name
     *
     * @mbg.generated
     */
    public String getOltDbTalbeViewName() {
        return oltDbTalbeViewName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.olt_db_talbe_view_name
     *
     * @param oltDbTalbeViewName the value for sys_table_desp.olt_db_talbe_view_name
     *
     * @mbg.generated
     */
    public void setOltDbTalbeViewName(String oltDbTalbeViewName) {
        this.oltDbTalbeViewName = oltDbTalbeViewName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.olt_db_talbe_view_desc
     *
     * @return the value of sys_table_desp.olt_db_talbe_view_desc
     *
     * @mbg.generated
     */
    public String getOltDbTalbeViewDesc() {
        return oltDbTalbeViewDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.olt_db_talbe_view_desc
     *
     * @param oltDbTalbeViewDesc the value for sys_table_desp.olt_db_talbe_view_desc
     *
     * @mbg.generated
     */
    public void setOltDbTalbeViewDesc(String oltDbTalbeViewDesc) {
        this.oltDbTalbeViewDesc = oltDbTalbeViewDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.olt_json_package_name
     *
     * @return the value of sys_table_desp.olt_json_package_name
     *
     * @mbg.generated
     */
    public String getOltJsonPackageName() {
        return oltJsonPackageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.olt_json_package_name
     *
     * @param oltJsonPackageName the value for sys_table_desp.olt_json_package_name
     *
     * @mbg.generated
     */
    public void setOltJsonPackageName(String oltJsonPackageName) {
        this.oltJsonPackageName = oltJsonPackageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.tenant_id
     *
     * @return the value of sys_table_desp.tenant_id
     *
     * @mbg.generated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.tenant_id
     *
     * @param tenantId the value for sys_table_desp.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.add_time
     *
     * @return the value of sys_table_desp.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.add_time
     *
     * @param addTime the value for sys_table_desp.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.add_by
     *
     * @return the value of sys_table_desp.add_by
     *
     * @mbg.generated
     */
    public String getAddBy() {
        return addBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.add_by
     *
     * @param addBy the value for sys_table_desp.add_by
     *
     * @mbg.generated
     */
    public void setAddBy(String addBy) {
        this.addBy = addBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.update_time
     *
     * @return the value of sys_table_desp.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.update_time
     *
     * @param updateTime the value for sys_table_desp.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.update_by
     *
     * @return the value of sys_table_desp.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.update_by
     *
     * @param updateBy the value for sys_table_desp.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_desp.deleted
     *
     * @return the value of sys_table_desp.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_desp.deleted
     *
     * @param deleted the value for sys_table_desp.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_table_desp
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", oltTableDesp=").append(oltTableDesp);
        sb.append(", oltPrimaryFieldName=").append(oltPrimaryFieldName);
        sb.append(", oltRemark=").append(oltRemark);
        sb.append(", oltParentId=").append(oltParentId);
        sb.append(", oltUniqueFieldNames=").append(oltUniqueFieldNames);
        sb.append(", oltUniqueFieldDeps=").append(oltUniqueFieldDeps);
        sb.append(", oltForeignFieldName=").append(oltForeignFieldName);
        sb.append(", oltForeignFieldDes=").append(oltForeignFieldDes);
        sb.append(", ordernumber=").append(ordernumber);
        sb.append(", oltDbTalbeViewName=").append(oltDbTalbeViewName);
        sb.append(", oltDbTalbeViewDesc=").append(oltDbTalbeViewDesc);
        sb.append(", oltJsonPackageName=").append(oltJsonPackageName);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", addTime=").append(addTime);
        sb.append(", addBy=").append(addBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_table_desp
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysTableDesp other = (SysTableDesp) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOltTableDesp() == null ? other.getOltTableDesp() == null : this.getOltTableDesp().equals(other.getOltTableDesp()))
            && (this.getOltPrimaryFieldName() == null ? other.getOltPrimaryFieldName() == null : this.getOltPrimaryFieldName().equals(other.getOltPrimaryFieldName()))
            && (this.getOltRemark() == null ? other.getOltRemark() == null : this.getOltRemark().equals(other.getOltRemark()))
            && (this.getOltParentId() == null ? other.getOltParentId() == null : this.getOltParentId().equals(other.getOltParentId()))
            && (Arrays.equals(this.getOltUniqueFieldNames(), other.getOltUniqueFieldNames()))
            && (Arrays.equals(this.getOltUniqueFieldDeps(), other.getOltUniqueFieldDeps()))
            && (this.getOltForeignFieldName() == null ? other.getOltForeignFieldName() == null : this.getOltForeignFieldName().equals(other.getOltForeignFieldName()))
            && (this.getOltForeignFieldDes() == null ? other.getOltForeignFieldDes() == null : this.getOltForeignFieldDes().equals(other.getOltForeignFieldDes()))
            && (this.getOrdernumber() == null ? other.getOrdernumber() == null : this.getOrdernumber().equals(other.getOrdernumber()))
            && (this.getOltDbTalbeViewName() == null ? other.getOltDbTalbeViewName() == null : this.getOltDbTalbeViewName().equals(other.getOltDbTalbeViewName()))
            && (this.getOltDbTalbeViewDesc() == null ? other.getOltDbTalbeViewDesc() == null : this.getOltDbTalbeViewDesc().equals(other.getOltDbTalbeViewDesc()))
            && (this.getOltJsonPackageName() == null ? other.getOltJsonPackageName() == null : this.getOltJsonPackageName().equals(other.getOltJsonPackageName()))
            && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getAddBy() == null ? other.getAddBy() == null : this.getAddBy().equals(other.getAddBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_table_desp
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOltTableDesp() == null) ? 0 : getOltTableDesp().hashCode());
        result = prime * result + ((getOltPrimaryFieldName() == null) ? 0 : getOltPrimaryFieldName().hashCode());
        result = prime * result + ((getOltRemark() == null) ? 0 : getOltRemark().hashCode());
        result = prime * result + ((getOltParentId() == null) ? 0 : getOltParentId().hashCode());
        result = prime * result + (Arrays.hashCode(getOltUniqueFieldNames()));
        result = prime * result + (Arrays.hashCode(getOltUniqueFieldDeps()));
        result = prime * result + ((getOltForeignFieldName() == null) ? 0 : getOltForeignFieldName().hashCode());
        result = prime * result + ((getOltForeignFieldDes() == null) ? 0 : getOltForeignFieldDes().hashCode());
        result = prime * result + ((getOrdernumber() == null) ? 0 : getOrdernumber().hashCode());
        result = prime * result + ((getOltDbTalbeViewName() == null) ? 0 : getOltDbTalbeViewName().hashCode());
        result = prime * result + ((getOltDbTalbeViewDesc() == null) ? 0 : getOltDbTalbeViewDesc().hashCode());
        result = prime * result + ((getOltJsonPackageName() == null) ? 0 : getOltJsonPackageName().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getAddBy() == null) ? 0 : getAddBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_table_desp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? IS_DELETED : NOT_DELETED);
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sys_table_desp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        oltTableDesp("olt_table_desp", "oltTableDesp", "VARCHAR", false),
        oltPrimaryFieldName("olt_primary_field_name", "oltPrimaryFieldName", "VARCHAR", false),
        oltRemark("olt_remark", "oltRemark", "VARCHAR", false),
        oltParentId("olt_parent_id", "oltParentId", "INTEGER", false),
        oltUniqueFieldNames("olt_unique_field_names", "oltUniqueFieldNames", "VARCHAR", false),
        oltUniqueFieldDeps("olt_unique_field_deps", "oltUniqueFieldDeps", "VARCHAR", false),
        oltForeignFieldName("olt_foreign_field_name", "oltForeignFieldName", "VARCHAR", false),
        oltForeignFieldDes("olt_foreign_field_des", "oltForeignFieldDes", "VARCHAR", false),
        ordernumber("ordernumber", "ordernumber", "INTEGER", false),
        oltDbTalbeViewName("olt_db_talbe_view_name", "oltDbTalbeViewName", "VARCHAR", false),
        oltDbTalbeViewDesc("olt_db_talbe_view_desc", "oltDbTalbeViewDesc", "VARCHAR", false),
        oltJsonPackageName("olt_json_package_name", "oltJsonPackageName", "VARCHAR", false),
        tenantId("tenant_id", "tenantId", "INTEGER", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        addBy("add_by", "addBy", "VARCHAR", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        updateBy("update_by", "updateBy", "VARCHAR", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}