package org.java.bi.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class SysTableFieldDesp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_table_field_desp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean NOT_DELETED = false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_table_field_desp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static final Boolean IS_DELETED = true;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olt_id
     *
     * @mbg.generated
     */
    private Integer oltId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.main_table_desp
     *
     * @mbg.generated
     */
    private String mainTableDesp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olf_field_name
     *
     * @mbg.generated
     */
    private String olfFieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olf_field_trans_name
     *
     * @mbg.generated
     */
    private String olfFieldTransName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olf_field_desp
     *
     * @mbg.generated
     */
    private String olfFieldDesp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olf_field_type
     *
     * @mbg.generated
     */
    private String olfFieldType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olf_dic_id
     *
     * @mbg.generated
     */
    private Integer olfDicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olf_dic_name
     *
     * @mbg.generated
     */
    private String olfDicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olf_remark
     *
     * @mbg.generated
     */
    private String olfRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.ordernumber
     *
     * @mbg.generated
     */
    private Integer ordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olt_table_name
     *
     * @mbg.generated
     */
    private String oltTableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olt_table_desp
     *
     * @mbg.generated
     */
    private String oltTableDesp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olt_table_field_label
     *
     * @mbg.generated
     */
    private String oltTableFieldLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olt_table_field_value
     *
     * @mbg.generated
     */
    private String oltTableFieldValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.olf_if_multi_value
     *
     * @mbg.generated
     */
    private Boolean olfIfMultiValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.tenant_id
     *
     * @mbg.generated
     */
    private Integer tenantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.add_time
     *
     * @mbg.generated
     */
    private LocalDateTime addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.add_by
     *
     * @mbg.generated
     */
    private String addBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_table_field_desp.deleted
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.id
     *
     * @return the value of sys_table_field_desp.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.id
     *
     * @param id the value for sys_table_field_desp.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olt_id
     *
     * @return the value of sys_table_field_desp.olt_id
     *
     * @mbg.generated
     */
    public Integer getOltId() {
        return oltId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olt_id
     *
     * @param oltId the value for sys_table_field_desp.olt_id
     *
     * @mbg.generated
     */
    public void setOltId(Integer oltId) {
        this.oltId = oltId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.main_table_desp
     *
     * @return the value of sys_table_field_desp.main_table_desp
     *
     * @mbg.generated
     */
    public String getMainTableDesp() {
        return mainTableDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.main_table_desp
     *
     * @param mainTableDesp the value for sys_table_field_desp.main_table_desp
     *
     * @mbg.generated
     */
    public void setMainTableDesp(String mainTableDesp) {
        this.mainTableDesp = mainTableDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olf_field_name
     *
     * @return the value of sys_table_field_desp.olf_field_name
     *
     * @mbg.generated
     */
    public String getOlfFieldName() {
        return olfFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olf_field_name
     *
     * @param olfFieldName the value for sys_table_field_desp.olf_field_name
     *
     * @mbg.generated
     */
    public void setOlfFieldName(String olfFieldName) {
        this.olfFieldName = olfFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olf_field_trans_name
     *
     * @return the value of sys_table_field_desp.olf_field_trans_name
     *
     * @mbg.generated
     */
    public String getOlfFieldTransName() {
        return olfFieldTransName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olf_field_trans_name
     *
     * @param olfFieldTransName the value for sys_table_field_desp.olf_field_trans_name
     *
     * @mbg.generated
     */
    public void setOlfFieldTransName(String olfFieldTransName) {
        this.olfFieldTransName = olfFieldTransName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olf_field_desp
     *
     * @return the value of sys_table_field_desp.olf_field_desp
     *
     * @mbg.generated
     */
    public String getOlfFieldDesp() {
        return olfFieldDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olf_field_desp
     *
     * @param olfFieldDesp the value for sys_table_field_desp.olf_field_desp
     *
     * @mbg.generated
     */
    public void setOlfFieldDesp(String olfFieldDesp) {
        this.olfFieldDesp = olfFieldDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olf_field_type
     *
     * @return the value of sys_table_field_desp.olf_field_type
     *
     * @mbg.generated
     */
    public String getOlfFieldType() {
        return olfFieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olf_field_type
     *
     * @param olfFieldType the value for sys_table_field_desp.olf_field_type
     *
     * @mbg.generated
     */
    public void setOlfFieldType(String olfFieldType) {
        this.olfFieldType = olfFieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olf_dic_id
     *
     * @return the value of sys_table_field_desp.olf_dic_id
     *
     * @mbg.generated
     */
    public Integer getOlfDicId() {
        return olfDicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olf_dic_id
     *
     * @param olfDicId the value for sys_table_field_desp.olf_dic_id
     *
     * @mbg.generated
     */
    public void setOlfDicId(Integer olfDicId) {
        this.olfDicId = olfDicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olf_dic_name
     *
     * @return the value of sys_table_field_desp.olf_dic_name
     *
     * @mbg.generated
     */
    public String getOlfDicName() {
        return olfDicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olf_dic_name
     *
     * @param olfDicName the value for sys_table_field_desp.olf_dic_name
     *
     * @mbg.generated
     */
    public void setOlfDicName(String olfDicName) {
        this.olfDicName = olfDicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olf_remark
     *
     * @return the value of sys_table_field_desp.olf_remark
     *
     * @mbg.generated
     */
    public String getOlfRemark() {
        return olfRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olf_remark
     *
     * @param olfRemark the value for sys_table_field_desp.olf_remark
     *
     * @mbg.generated
     */
    public void setOlfRemark(String olfRemark) {
        this.olfRemark = olfRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.ordernumber
     *
     * @return the value of sys_table_field_desp.ordernumber
     *
     * @mbg.generated
     */
    public Integer getOrdernumber() {
        return ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.ordernumber
     *
     * @param ordernumber the value for sys_table_field_desp.ordernumber
     *
     * @mbg.generated
     */
    public void setOrdernumber(Integer ordernumber) {
        this.ordernumber = ordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olt_table_name
     *
     * @return the value of sys_table_field_desp.olt_table_name
     *
     * @mbg.generated
     */
    public String getOltTableName() {
        return oltTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olt_table_name
     *
     * @param oltTableName the value for sys_table_field_desp.olt_table_name
     *
     * @mbg.generated
     */
    public void setOltTableName(String oltTableName) {
        this.oltTableName = oltTableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olt_table_desp
     *
     * @return the value of sys_table_field_desp.olt_table_desp
     *
     * @mbg.generated
     */
    public String getOltTableDesp() {
        return oltTableDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olt_table_desp
     *
     * @param oltTableDesp the value for sys_table_field_desp.olt_table_desp
     *
     * @mbg.generated
     */
    public void setOltTableDesp(String oltTableDesp) {
        this.oltTableDesp = oltTableDesp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olt_table_field_label
     *
     * @return the value of sys_table_field_desp.olt_table_field_label
     *
     * @mbg.generated
     */
    public String getOltTableFieldLabel() {
        return oltTableFieldLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olt_table_field_label
     *
     * @param oltTableFieldLabel the value for sys_table_field_desp.olt_table_field_label
     *
     * @mbg.generated
     */
    public void setOltTableFieldLabel(String oltTableFieldLabel) {
        this.oltTableFieldLabel = oltTableFieldLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olt_table_field_value
     *
     * @return the value of sys_table_field_desp.olt_table_field_value
     *
     * @mbg.generated
     */
    public String getOltTableFieldValue() {
        return oltTableFieldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olt_table_field_value
     *
     * @param oltTableFieldValue the value for sys_table_field_desp.olt_table_field_value
     *
     * @mbg.generated
     */
    public void setOltTableFieldValue(String oltTableFieldValue) {
        this.oltTableFieldValue = oltTableFieldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.olf_if_multi_value
     *
     * @return the value of sys_table_field_desp.olf_if_multi_value
     *
     * @mbg.generated
     */
    public Boolean getOlfIfMultiValue() {
        return olfIfMultiValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.olf_if_multi_value
     *
     * @param olfIfMultiValue the value for sys_table_field_desp.olf_if_multi_value
     *
     * @mbg.generated
     */
    public void setOlfIfMultiValue(Boolean olfIfMultiValue) {
        this.olfIfMultiValue = olfIfMultiValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.tenant_id
     *
     * @return the value of sys_table_field_desp.tenant_id
     *
     * @mbg.generated
     */
    public Integer getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.tenant_id
     *
     * @param tenantId the value for sys_table_field_desp.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(Integer tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.add_time
     *
     * @return the value of sys_table_field_desp.add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.add_time
     *
     * @param addTime the value for sys_table_field_desp.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(LocalDateTime addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.add_by
     *
     * @return the value of sys_table_field_desp.add_by
     *
     * @mbg.generated
     */
    public String getAddBy() {
        return addBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.add_by
     *
     * @param addBy the value for sys_table_field_desp.add_by
     *
     * @mbg.generated
     */
    public void setAddBy(String addBy) {
        this.addBy = addBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.update_time
     *
     * @return the value of sys_table_field_desp.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.update_time
     *
     * @param updateTime the value for sys_table_field_desp.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.update_by
     *
     * @return the value of sys_table_field_desp.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.update_by
     *
     * @param updateBy the value for sys_table_field_desp.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_table_field_desp.deleted
     *
     * @return the value of sys_table_field_desp.deleted
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_table_field_desp.deleted
     *
     * @param deleted the value for sys_table_field_desp.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_table_field_desp
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", oltId=").append(oltId);
        sb.append(", mainTableDesp=").append(mainTableDesp);
        sb.append(", olfFieldName=").append(olfFieldName);
        sb.append(", olfFieldTransName=").append(olfFieldTransName);
        sb.append(", olfFieldDesp=").append(olfFieldDesp);
        sb.append(", olfFieldType=").append(olfFieldType);
        sb.append(", olfDicId=").append(olfDicId);
        sb.append(", olfDicName=").append(olfDicName);
        sb.append(", olfRemark=").append(olfRemark);
        sb.append(", ordernumber=").append(ordernumber);
        sb.append(", oltTableName=").append(oltTableName);
        sb.append(", oltTableDesp=").append(oltTableDesp);
        sb.append(", oltTableFieldLabel=").append(oltTableFieldLabel);
        sb.append(", oltTableFieldValue=").append(oltTableFieldValue);
        sb.append(", olfIfMultiValue=").append(olfIfMultiValue);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", addTime=").append(addTime);
        sb.append(", addBy=").append(addBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_table_field_desp
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysTableFieldDesp other = (SysTableFieldDesp) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOltId() == null ? other.getOltId() == null : this.getOltId().equals(other.getOltId()))
            && (this.getMainTableDesp() == null ? other.getMainTableDesp() == null : this.getMainTableDesp().equals(other.getMainTableDesp()))
            && (this.getOlfFieldName() == null ? other.getOlfFieldName() == null : this.getOlfFieldName().equals(other.getOlfFieldName()))
            && (this.getOlfFieldTransName() == null ? other.getOlfFieldTransName() == null : this.getOlfFieldTransName().equals(other.getOlfFieldTransName()))
            && (this.getOlfFieldDesp() == null ? other.getOlfFieldDesp() == null : this.getOlfFieldDesp().equals(other.getOlfFieldDesp()))
            && (this.getOlfFieldType() == null ? other.getOlfFieldType() == null : this.getOlfFieldType().equals(other.getOlfFieldType()))
            && (this.getOlfDicId() == null ? other.getOlfDicId() == null : this.getOlfDicId().equals(other.getOlfDicId()))
            && (this.getOlfDicName() == null ? other.getOlfDicName() == null : this.getOlfDicName().equals(other.getOlfDicName()))
            && (this.getOlfRemark() == null ? other.getOlfRemark() == null : this.getOlfRemark().equals(other.getOlfRemark()))
            && (this.getOrdernumber() == null ? other.getOrdernumber() == null : this.getOrdernumber().equals(other.getOrdernumber()))
            && (this.getOltTableName() == null ? other.getOltTableName() == null : this.getOltTableName().equals(other.getOltTableName()))
            && (this.getOltTableDesp() == null ? other.getOltTableDesp() == null : this.getOltTableDesp().equals(other.getOltTableDesp()))
            && (this.getOltTableFieldLabel() == null ? other.getOltTableFieldLabel() == null : this.getOltTableFieldLabel().equals(other.getOltTableFieldLabel()))
            && (this.getOltTableFieldValue() == null ? other.getOltTableFieldValue() == null : this.getOltTableFieldValue().equals(other.getOltTableFieldValue()))
            && (this.getOlfIfMultiValue() == null ? other.getOlfIfMultiValue() == null : this.getOlfIfMultiValue().equals(other.getOlfIfMultiValue()))
            && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getAddBy() == null ? other.getAddBy() == null : this.getAddBy().equals(other.getAddBy()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_table_field_desp
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOltId() == null) ? 0 : getOltId().hashCode());
        result = prime * result + ((getMainTableDesp() == null) ? 0 : getMainTableDesp().hashCode());
        result = prime * result + ((getOlfFieldName() == null) ? 0 : getOlfFieldName().hashCode());
        result = prime * result + ((getOlfFieldTransName() == null) ? 0 : getOlfFieldTransName().hashCode());
        result = prime * result + ((getOlfFieldDesp() == null) ? 0 : getOlfFieldDesp().hashCode());
        result = prime * result + ((getOlfFieldType() == null) ? 0 : getOlfFieldType().hashCode());
        result = prime * result + ((getOlfDicId() == null) ? 0 : getOlfDicId().hashCode());
        result = prime * result + ((getOlfDicName() == null) ? 0 : getOlfDicName().hashCode());
        result = prime * result + ((getOlfRemark() == null) ? 0 : getOlfRemark().hashCode());
        result = prime * result + ((getOrdernumber() == null) ? 0 : getOrdernumber().hashCode());
        result = prime * result + ((getOltTableName() == null) ? 0 : getOltTableName().hashCode());
        result = prime * result + ((getOltTableDesp() == null) ? 0 : getOltTableDesp().hashCode());
        result = prime * result + ((getOltTableFieldLabel() == null) ? 0 : getOltTableFieldLabel().hashCode());
        result = prime * result + ((getOltTableFieldValue() == null) ? 0 : getOltTableFieldValue().hashCode());
        result = prime * result + ((getOlfIfMultiValue() == null) ? 0 : getOlfIfMultiValue().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getAddBy() == null) ? 0 : getAddBy().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_table_field_desp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void andLogicalDeleted(boolean deleted) {
        setDeleted(deleted ? IS_DELETED : NOT_DELETED);
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table sys_table_field_desp
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        oltId("olt_id", "oltId", "INTEGER", false),
        mainTableDesp("main_table_desp", "mainTableDesp", "VARCHAR", false),
        olfFieldName("olf_field_name", "olfFieldName", "VARCHAR", false),
        olfFieldTransName("olf_field_trans_name", "olfFieldTransName", "VARCHAR", false),
        olfFieldDesp("olf_field_desp", "olfFieldDesp", "VARCHAR", false),
        olfFieldType("olf_field_type", "olfFieldType", "VARCHAR", false),
        olfDicId("olf_dic_id", "olfDicId", "INTEGER", false),
        olfDicName("olf_dic_name", "olfDicName", "VARCHAR", false),
        olfRemark("olf_remark", "olfRemark", "VARCHAR", false),
        ordernumber("ordernumber", "ordernumber", "INTEGER", false),
        oltTableName("olt_table_name", "oltTableName", "VARCHAR", false),
        oltTableDesp("olt_table_desp", "oltTableDesp", "VARCHAR", false),
        oltTableFieldLabel("olt_table_field_label", "oltTableFieldLabel", "VARCHAR", false),
        oltTableFieldValue("olt_table_field_value", "oltTableFieldValue", "VARCHAR", false),
        olfIfMultiValue("olf_if_multi_value", "olfIfMultiValue", "BIT", false),
        tenantId("tenant_id", "tenantId", "INTEGER", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        addBy("add_by", "addBy", "VARCHAR", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        updateBy("update_by", "updateBy", "VARCHAR", false),
        deleted("deleted", "deleted", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table sys_table_field_desp
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}