package org.java.bi.db.domain;

import java.util.ArrayList;
import java.util.List;

public class ViewTableFieldDefExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    public ViewTableFieldDefExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public ViewTableFieldDefExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public ViewTableFieldDefExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Criteria newAndCreateCriteria() {
        ViewTableFieldDefExample example = new ViewTableFieldDefExample();
        return example.createCriteria();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTableCommentIsNull() {
            addCriterion("table_comment is null");
            return (Criteria) this;
        }

        public Criteria andTableCommentIsNotNull() {
            addCriterion("table_comment is not null");
            return (Criteria) this;
        }

        public Criteria andTableCommentEqualTo(String value) {
            addCriterion("table_comment =", value, "tableComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableCommentEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_comment = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableCommentNotEqualTo(String value) {
            addCriterion("table_comment <>", value, "tableComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableCommentNotEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_comment <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableCommentGreaterThan(String value) {
            addCriterion("table_comment >", value, "tableComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableCommentGreaterThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_comment > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableCommentGreaterThanOrEqualTo(String value) {
            addCriterion("table_comment >=", value, "tableComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableCommentGreaterThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_comment >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableCommentLessThan(String value) {
            addCriterion("table_comment <", value, "tableComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableCommentLessThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_comment < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableCommentLessThanOrEqualTo(String value) {
            addCriterion("table_comment <=", value, "tableComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableCommentLessThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_comment <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableCommentLike(String value) {
            addCriterion("table_comment like", value, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentNotLike(String value) {
            addCriterion("table_comment not like", value, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentIn(List<String> values) {
            addCriterion("table_comment in", values, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentNotIn(List<String> values) {
            addCriterion("table_comment not in", values, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentBetween(String value1, String value2) {
            addCriterion("table_comment between", value1, value2, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableCommentNotBetween(String value1, String value2) {
            addCriterion("table_comment not between", value1, value2, "tableComment");
            return (Criteria) this;
        }

        public Criteria andTableTypeIsNull() {
            addCriterion("table_type is null");
            return (Criteria) this;
        }

        public Criteria andTableTypeIsNotNull() {
            addCriterion("table_type is not null");
            return (Criteria) this;
        }

        public Criteria andTableTypeEqualTo(String value) {
            addCriterion("table_type =", value, "tableType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableTypeEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_type = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableTypeNotEqualTo(String value) {
            addCriterion("table_type <>", value, "tableType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableTypeNotEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_type <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableTypeGreaterThan(String value) {
            addCriterion("table_type >", value, "tableType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableTypeGreaterThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_type > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableTypeGreaterThanOrEqualTo(String value) {
            addCriterion("table_type >=", value, "tableType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableTypeGreaterThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_type >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableTypeLessThan(String value) {
            addCriterion("table_type <", value, "tableType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableTypeLessThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_type < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableTypeLessThanOrEqualTo(String value) {
            addCriterion("table_type <=", value, "tableType");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableTypeLessThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("table_type <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableTypeLike(String value) {
            addCriterion("table_type like", value, "tableType");
            return (Criteria) this;
        }

        public Criteria andTableTypeNotLike(String value) {
            addCriterion("table_type not like", value, "tableType");
            return (Criteria) this;
        }

        public Criteria andTableTypeIn(List<String> values) {
            addCriterion("table_type in", values, "tableType");
            return (Criteria) this;
        }

        public Criteria andTableTypeNotIn(List<String> values) {
            addCriterion("table_type not in", values, "tableType");
            return (Criteria) this;
        }

        public Criteria andTableTypeBetween(String value1, String value2) {
            addCriterion("table_type between", value1, value2, "tableType");
            return (Criteria) this;
        }

        public Criteria andTableTypeNotBetween(String value1, String value2) {
            addCriterion("table_type not between", value1, value2, "tableType");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNull() {
            addCriterion("`table_name` is null");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNotNull() {
            addCriterion("`table_name` is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameEqualTo(String value) {
            addCriterion("`table_name` =", value, "tableName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableNameEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`table_name` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableNameNotEqualTo(String value) {
            addCriterion("`table_name` <>", value, "tableName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableNameNotEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`table_name` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThan(String value) {
            addCriterion("`table_name` >", value, "tableName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableNameGreaterThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`table_name` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("`table_name` >=", value, "tableName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableNameGreaterThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`table_name` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableNameLessThan(String value) {
            addCriterion("`table_name` <", value, "tableName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableNameLessThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`table_name` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableNameLessThanOrEqualTo(String value) {
            addCriterion("`table_name` <=", value, "tableName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTableNameLessThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`table_name` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTableNameLike(String value) {
            addCriterion("`table_name` like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotLike(String value) {
            addCriterion("`table_name` not like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIn(List<String> values) {
            addCriterion("`table_name` in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotIn(List<String> values) {
            addCriterion("`table_name` not in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameBetween(String value1, String value2) {
            addCriterion("`table_name` between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotBetween(String value1, String value2) {
            addCriterion("`table_name` not between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andColumnNameIsNull() {
            addCriterion("`column_name` is null");
            return (Criteria) this;
        }

        public Criteria andColumnNameIsNotNull() {
            addCriterion("`column_name` is not null");
            return (Criteria) this;
        }

        public Criteria andColumnNameEqualTo(String value) {
            addCriterion("`column_name` =", value, "columnName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnNameEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`column_name` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnNameNotEqualTo(String value) {
            addCriterion("`column_name` <>", value, "columnName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnNameNotEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`column_name` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThan(String value) {
            addCriterion("`column_name` >", value, "columnName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnNameGreaterThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`column_name` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThanOrEqualTo(String value) {
            addCriterion("`column_name` >=", value, "columnName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnNameGreaterThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`column_name` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThan(String value) {
            addCriterion("`column_name` <", value, "columnName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnNameLessThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`column_name` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThanOrEqualTo(String value) {
            addCriterion("`column_name` <=", value, "columnName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnNameLessThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("`column_name` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnNameLike(String value) {
            addCriterion("`column_name` like", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotLike(String value) {
            addCriterion("`column_name` not like", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameIn(List<String> values) {
            addCriterion("`column_name` in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotIn(List<String> values) {
            addCriterion("`column_name` not in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameBetween(String value1, String value2) {
            addCriterion("`column_name` between", value1, value2, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotBetween(String value1, String value2) {
            addCriterion("`column_name` not between", value1, value2, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnCommentIsNull() {
            addCriterion("column_comment is null");
            return (Criteria) this;
        }

        public Criteria andColumnCommentIsNotNull() {
            addCriterion("column_comment is not null");
            return (Criteria) this;
        }

        public Criteria andColumnCommentEqualTo(String value) {
            addCriterion("column_comment =", value, "columnComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnCommentEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("column_comment = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnCommentNotEqualTo(String value) {
            addCriterion("column_comment <>", value, "columnComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnCommentNotEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("column_comment <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnCommentGreaterThan(String value) {
            addCriterion("column_comment >", value, "columnComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnCommentGreaterThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("column_comment > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnCommentGreaterThanOrEqualTo(String value) {
            addCriterion("column_comment >=", value, "columnComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnCommentGreaterThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("column_comment >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnCommentLessThan(String value) {
            addCriterion("column_comment <", value, "columnComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnCommentLessThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("column_comment < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnCommentLessThanOrEqualTo(String value) {
            addCriterion("column_comment <=", value, "columnComment");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andColumnCommentLessThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("column_comment <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andColumnCommentLike(String value) {
            addCriterion("column_comment like", value, "columnComment");
            return (Criteria) this;
        }

        public Criteria andColumnCommentNotLike(String value) {
            addCriterion("column_comment not like", value, "columnComment");
            return (Criteria) this;
        }

        public Criteria andColumnCommentIn(List<String> values) {
            addCriterion("column_comment in", values, "columnComment");
            return (Criteria) this;
        }

        public Criteria andColumnCommentNotIn(List<String> values) {
            addCriterion("column_comment not in", values, "columnComment");
            return (Criteria) this;
        }

        public Criteria andColumnCommentBetween(String value1, String value2) {
            addCriterion("column_comment between", value1, value2, "columnComment");
            return (Criteria) this;
        }

        public Criteria andColumnCommentNotBetween(String value1, String value2) {
            addCriterion("column_comment not between", value1, value2, "columnComment");
            return (Criteria) this;
        }

        public Criteria andLeiXingIsNull() {
            addCriterion("lei_xing is null");
            return (Criteria) this;
        }

        public Criteria andLeiXingIsNotNull() {
            addCriterion("lei_xing is not null");
            return (Criteria) this;
        }

        public Criteria andLeiXingEqualTo(String value) {
            addCriterion("lei_xing =", value, "leiXing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLeiXingEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("lei_xing = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLeiXingNotEqualTo(String value) {
            addCriterion("lei_xing <>", value, "leiXing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLeiXingNotEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("lei_xing <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLeiXingGreaterThan(String value) {
            addCriterion("lei_xing >", value, "leiXing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLeiXingGreaterThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("lei_xing > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLeiXingGreaterThanOrEqualTo(String value) {
            addCriterion("lei_xing >=", value, "leiXing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLeiXingGreaterThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("lei_xing >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLeiXingLessThan(String value) {
            addCriterion("lei_xing <", value, "leiXing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLeiXingLessThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("lei_xing < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLeiXingLessThanOrEqualTo(String value) {
            addCriterion("lei_xing <=", value, "leiXing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLeiXingLessThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("lei_xing <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andLeiXingLike(String value) {
            addCriterion("lei_xing like", value, "leiXing");
            return (Criteria) this;
        }

        public Criteria andLeiXingNotLike(String value) {
            addCriterion("lei_xing not like", value, "leiXing");
            return (Criteria) this;
        }

        public Criteria andLeiXingIn(List<String> values) {
            addCriterion("lei_xing in", values, "leiXing");
            return (Criteria) this;
        }

        public Criteria andLeiXingNotIn(List<String> values) {
            addCriterion("lei_xing not in", values, "leiXing");
            return (Criteria) this;
        }

        public Criteria andLeiXingBetween(String value1, String value2) {
            addCriterion("lei_xing between", value1, value2, "leiXing");
            return (Criteria) this;
        }

        public Criteria andLeiXingNotBetween(String value1, String value2) {
            addCriterion("lei_xing not between", value1, value2, "leiXing");
            return (Criteria) this;
        }

        public Criteria andFieldLengthIsNull() {
            addCriterion("field_length is null");
            return (Criteria) this;
        }

        public Criteria andFieldLengthIsNotNull() {
            addCriterion("field_length is not null");
            return (Criteria) this;
        }

        public Criteria andFieldLengthEqualTo(Long value) {
            addCriterion("field_length =", value, "fieldLength");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldLengthEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_length = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldLengthNotEqualTo(Long value) {
            addCriterion("field_length <>", value, "fieldLength");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldLengthNotEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_length <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldLengthGreaterThan(Long value) {
            addCriterion("field_length >", value, "fieldLength");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldLengthGreaterThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_length > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldLengthGreaterThanOrEqualTo(Long value) {
            addCriterion("field_length >=", value, "fieldLength");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldLengthGreaterThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_length >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldLengthLessThan(Long value) {
            addCriterion("field_length <", value, "fieldLength");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldLengthLessThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_length < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldLengthLessThanOrEqualTo(Long value) {
            addCriterion("field_length <=", value, "fieldLength");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldLengthLessThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_length <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldLengthIn(List<Long> values) {
            addCriterion("field_length in", values, "fieldLength");
            return (Criteria) this;
        }

        public Criteria andFieldLengthNotIn(List<Long> values) {
            addCriterion("field_length not in", values, "fieldLength");
            return (Criteria) this;
        }

        public Criteria andFieldLengthBetween(Long value1, Long value2) {
            addCriterion("field_length between", value1, value2, "fieldLength");
            return (Criteria) this;
        }

        public Criteria andFieldLengthNotBetween(Long value1, Long value2) {
            addCriterion("field_length not between", value1, value2, "fieldLength");
            return (Criteria) this;
        }

        public Criteria andFieldIfNullIsNull() {
            addCriterion("field_if_null is null");
            return (Criteria) this;
        }

        public Criteria andFieldIfNullIsNotNull() {
            addCriterion("field_if_null is not null");
            return (Criteria) this;
        }

        public Criteria andFieldIfNullEqualTo(String value) {
            addCriterion("field_if_null =", value, "fieldIfNull");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldIfNullEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_if_null = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldIfNullNotEqualTo(String value) {
            addCriterion("field_if_null <>", value, "fieldIfNull");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldIfNullNotEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_if_null <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldIfNullGreaterThan(String value) {
            addCriterion("field_if_null >", value, "fieldIfNull");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldIfNullGreaterThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_if_null > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldIfNullGreaterThanOrEqualTo(String value) {
            addCriterion("field_if_null >=", value, "fieldIfNull");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldIfNullGreaterThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_if_null >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldIfNullLessThan(String value) {
            addCriterion("field_if_null <", value, "fieldIfNull");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldIfNullLessThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_if_null < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldIfNullLessThanOrEqualTo(String value) {
            addCriterion("field_if_null <=", value, "fieldIfNull");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldIfNullLessThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_if_null <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldIfNullLike(String value) {
            addCriterion("field_if_null like", value, "fieldIfNull");
            return (Criteria) this;
        }

        public Criteria andFieldIfNullNotLike(String value) {
            addCriterion("field_if_null not like", value, "fieldIfNull");
            return (Criteria) this;
        }

        public Criteria andFieldIfNullIn(List<String> values) {
            addCriterion("field_if_null in", values, "fieldIfNull");
            return (Criteria) this;
        }

        public Criteria andFieldIfNullNotIn(List<String> values) {
            addCriterion("field_if_null not in", values, "fieldIfNull");
            return (Criteria) this;
        }

        public Criteria andFieldIfNullBetween(String value1, String value2) {
            addCriterion("field_if_null between", value1, value2, "fieldIfNull");
            return (Criteria) this;
        }

        public Criteria andFieldIfNullNotBetween(String value1, String value2) {
            addCriterion("field_if_null not between", value1, value2, "fieldIfNull");
            return (Criteria) this;
        }

        public Criteria andFieldDefaultIsNull() {
            addCriterion("field_default is null");
            return (Criteria) this;
        }

        public Criteria andFieldDefaultIsNotNull() {
            addCriterion("field_default is not null");
            return (Criteria) this;
        }

        public Criteria andFieldDefaultEqualTo(String value) {
            addCriterion("field_default =", value, "fieldDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldDefaultEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_default = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldDefaultNotEqualTo(String value) {
            addCriterion("field_default <>", value, "fieldDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldDefaultNotEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_default <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldDefaultGreaterThan(String value) {
            addCriterion("field_default >", value, "fieldDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldDefaultGreaterThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_default > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldDefaultGreaterThanOrEqualTo(String value) {
            addCriterion("field_default >=", value, "fieldDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldDefaultGreaterThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_default >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldDefaultLessThan(String value) {
            addCriterion("field_default <", value, "fieldDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldDefaultLessThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_default < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldDefaultLessThanOrEqualTo(String value) {
            addCriterion("field_default <=", value, "fieldDefault");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andFieldDefaultLessThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("field_default <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andFieldDefaultLike(String value) {
            addCriterion("field_default like", value, "fieldDefault");
            return (Criteria) this;
        }

        public Criteria andFieldDefaultNotLike(String value) {
            addCriterion("field_default not like", value, "fieldDefault");
            return (Criteria) this;
        }

        public Criteria andFieldDefaultIn(List<String> values) {
            addCriterion("field_default in", values, "fieldDefault");
            return (Criteria) this;
        }

        public Criteria andFieldDefaultNotIn(List<String> values) {
            addCriterion("field_default not in", values, "fieldDefault");
            return (Criteria) this;
        }

        public Criteria andFieldDefaultBetween(String value1, String value2) {
            addCriterion("field_default between", value1, value2, "fieldDefault");
            return (Criteria) this;
        }

        public Criteria andFieldDefaultNotBetween(String value1, String value2) {
            addCriterion("field_default not between", value1, value2, "fieldDefault");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Integer value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeletedEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("deleted = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Integer value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeletedNotEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("deleted <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Integer value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeletedGreaterThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("deleted > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeletedGreaterThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("deleted >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Integer value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeletedLessThanColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("deleted < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeletedLessThanOrEqualToColumn(ViewTableFieldDefWithBLOBs.Column column) {
            addCriterion(new StringBuilder("deleted <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Integer> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Integer> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Integer value1, Integer value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_table_field_def
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private ViewTableFieldDefExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(ViewTableFieldDefExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public ViewTableFieldDefExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andLogicalDeleted(boolean deleted) {
            return deleted ? andDeletedEqualTo(ViewTableFieldDefWithBLOBs.IS_DELETED) : andDeletedNotEqualTo(ViewTableFieldDefWithBLOBs.IS_DELETED);
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table view_table_field_def
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table view_table_field_def
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table view_table_field_def
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}